const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA=process.env.DATA_DIR||path.join(ROOT,'data'),CONFIG=path.join(DATA,'site-config.json'),SEED=path.join(ROOT,'data','site-config.json'),BACKUPS=path.join(DATA,'backups');
const PORT=process.env.PORT||3000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'',sessions=new Map(),youtubeCache=new Map();
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(BACKUPS,{recursive:true});if(!fs.existsSync(CONFIG)&&fs.existsSync(SEED))fs.copyFileSync(SEED,CONFIG);
try{if(fs.existsSync(CONFIG)){const x=JSON.parse(fs.readFileSync(CONFIG,'utf8'));x.channels=x.channels||{};x.channels.main=x.channels.main||{};x.channels.sub=x.channels.sub||{};x.channels.main.name='차트서포터의 유튜브 HOT';x.channels.sub.name='의리코인의 유튜브 HOT';x.youtubeAuto={enabled:false,mainChannelId:'',subChannelId:'',count:3,cacheMinutes:10,...(x.youtubeAuto||{})};if((x.guideContentVersion||0)<1&&fs.existsSync(SEED)){const seed=JSON.parse(fs.readFileSync(SEED,'utf8'));x.guides=x.guides||{};x.guides.signup=seed.guides.signup;x.pages=x.pages||{};for(const k of ['signup','deposit','withdraw','trade','benefit'])x.pages[k]=seed.pages[k];x.guideContentVersion=1}fs.writeFileSync(CONFIG,JSON.stringify(x,null,2),'utf8')}}catch(e){console.error('config migration failed',e)}
function send(res,status,body,type='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function json(res,status,obj){send(res,status,JSON.stringify(obj),'application/json; charset=utf-8')}
function readBody(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2e6){reject(new Error('too large'));req.destroy()}});req.on('end',()=>resolve(d));req.on('error',reject)})}
function readBuffer(req){return new Promise((resolve,reject)=>{const chunks=[];let n=0;req.on('data',c=>{n+=c.length;if(n>10e6){reject(new Error('too large'));req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]}))}
function isAdmin(req){const t=parseCookies(req).freedom_admin;return t&&sessions.has(t)}
function mime(file){const e=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.json':'application/json; charset=utf-8'})[e]||'application/octet-stream'}
function serveFile(res,file){if(!fs.existsSync(file)||!fs.statSync(file).isFile())return false;res.writeHead(200,{'Content-Type':mime(file)});fs.createReadStream(file).pipe(res);return true}
function loadConfig(){return JSON.parse(fs.readFileSync(CONFIG,'utf8'))}
function saveConfig(obj){const stamp=new Date().toISOString().replace(/[:.]/g,'-');if(fs.existsSync(CONFIG))fs.copyFileSync(CONFIG,path.join(BACKUPS,`site-config-${stamp}.json`));const tmp=CONFIG+'.tmp';fs.writeFileSync(tmp,JSON.stringify(obj,null,2),'utf8');fs.renameSync(tmp,CONFIG)}
function getYouTubeApiKey(){const env=(process.env.YOUTUBE_API_KEY||'').trim();if(env)return env;const p=path.join(DATA,'youtube-api-key.txt');return fs.existsSync(p)?fs.readFileSync(p,'utf8').trim():''}
async function ytApi(resource,params,key){const u=new URL('https://www.googleapis.com/youtube/v3/'+resource);for(const [k,v] of Object.entries({...params,key}))u.searchParams.set(k,String(v));const r=await fetch(u);const body=await r.json().catch(()=>({}));if(!r.ok){const msg=body?.error?.message||('YouTube API '+r.status);const e=new Error(msg);e.status=r.status;throw e}return body}
async function latestForChannel(channelId,limit,cacheMinutes,key){if(!channelId)return[];const ck=channelId+'|'+limit,hit=youtubeCache.get(ck),ttl=Math.max(1,cacheMinutes)*60000;if(hit&&Date.now()-hit.time<ttl)return hit.items;const ch=await ytApi('channels',{part:'contentDetails,snippet',id:channelId},key);if(!ch.items?.length)throw new Error('채널 ID를 확인해 주세요.');const uploads=ch.items[0]?.contentDetails?.relatedPlaylists?.uploads;let items=[];if(uploads){try{const pl=await ytApi('playlistItems',{part:'snippet,contentDetails',playlistId:uploads,maxResults:Math.min(6,Math.max(1,limit))},key);items=(pl.items||[]).map(x=>{const sn=x.snippet||{},vid=x.contentDetails?.videoId||sn.resourceId?.videoId||'',thumb=sn.thumbnails?.maxres?.url||sn.thumbnails?.standard?.url||sn.thumbnails?.high?.url||sn.thumbnails?.medium?.url||sn.thumbnails?.default?.url||'';return{title:sn.title||'YouTube 영상',meta:'최신 영상 · '+(sn.publishedAt?new Date(sn.publishedAt).toLocaleDateString('ko-KR'):'YouTube'),thumbnail:thumb,url:vid?'https://www.youtube.com/watch?v='+vid:'#',videoId:vid,publishedAt:sn.publishedAt||''}}).filter(x=>x.videoId)}catch(e){if(e.status!==404)throw e}}if(!items.length){const sh=await ytApi('search',{part:'snippet',channelId,order:'date',type:'video',maxResults:Math.min(6,Math.max(1,limit))},key);items=(sh.items||[]).map(x=>{const sn=x.snippet||{},vid=x.id?.videoId||'',thumb=sn.thumbnails?.high?.url||sn.thumbnails?.medium?.url||sn.thumbnails?.default?.url||(vid?'https://i.ytimg.com/vi/'+vid+'/hqdefault.jpg':'');return{title:sn.title||'YouTube 영상',meta:'최신 영상 · '+(sn.publishedAt?new Date(sn.publishedAt).toLocaleDateString('ko-KR'):'YouTube'),thumbnail:thumb,url:vid?'https://www.youtube.com/watch?v='+vid:'#',videoId:vid,publishedAt:sn.publishedAt||''}}).filter(x=>x.videoId)}youtubeCache.set(ck,{time:Date.now(),items});return items}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const pathname=decodeURIComponent(u.pathname);
if(pathname==='/health')return json(res,200,{ok:true});
if(pathname==='/uploads/hero-image'&&req.method==='GET'){const fp=path.join(DATA,'hero-image.bin'),mp=path.join(DATA,'hero-image.mime');if(!fs.existsSync(fp))return send(res,404,'Not found');const mt=fs.existsSync(mp)?fs.readFileSync(mp,'utf8'):'image/jpeg';res.writeHead(200,{'Content-Type':mt,'Cache-Control':'no-cache'});return fs.createReadStream(fp).pipe(res)}
if(pathname==='/api/admin/hero-image'&&req.method==='POST'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});const mt=(req.headers['content-type']||'').split(';')[0].trim().toLowerCase();if(!['image/jpeg','image/png','image/webp'].includes(mt))return json(res,415,{error:'unsupported_image_type'});const buf=await readBuffer(req);if(!buf.length)return json(res,400,{error:'empty_file'});fs.writeFileSync(path.join(DATA,'hero-image.bin'),buf);fs.writeFileSync(path.join(DATA,'hero-image.mime'),mt,'utf8');return json(res,200,{ok:true,bytes:buf.length,url:'/uploads/hero-image'})}
if(pathname==='/api/admin/hero-image'&&req.method==='DELETE'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});for(const n of ['hero-image.bin','hero-image.mime']){const p=path.join(DATA,n);if(fs.existsSync(p))fs.unlinkSync(p)}return json(res,200,{ok:true})}
if(pathname==='/uploads/orangex-image'&&req.method==='GET'){const fp=path.join(DATA,'orangex-image.bin'),mp=path.join(DATA,'orangex-image.mime');if(fs.existsSync(fp)){const mt=fs.existsSync(mp)?fs.readFileSync(mp,'utf8'):'image/jpeg';res.writeHead(200,{'Content-Type':mt,'Cache-Control':'no-cache'});return fs.createReadStream(fp).pipe(res)}const fallback=path.join(PUBLIC,'assets','orangex-visual.webp');return serveFile(res,fallback)||send(res,404,'Not found')}
if(pathname==='/api/admin/orangex-image'&&req.method==='POST'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});const mt=(req.headers['content-type']||'').split(';')[0].trim().toLowerCase();if(!['image/jpeg','image/png','image/webp'].includes(mt))return json(res,415,{error:'unsupported_image_type'});const buf=await readBuffer(req);if(!buf.length)return json(res,400,{error:'empty_file'});fs.writeFileSync(path.join(DATA,'orangex-image.bin'),buf);fs.writeFileSync(path.join(DATA,'orangex-image.mime'),mt,'utf8');return json(res,200,{ok:true,bytes:buf.length,url:'/uploads/orangex-image'})}
if(pathname==='/api/admin/orangex-image'&&req.method==='DELETE'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});for(const n of ['orangex-image.bin','orangex-image.mime']){const p=path.join(DATA,n);if(fs.existsSync(p))fs.unlinkSync(p)}return json(res,200,{ok:true})}
if(pathname==='/api/youtube/latest'&&req.method==='GET'){const cfg=loadConfig(),y=cfg.youtubeAuto||{};if(!y.enabled)return json(res,200,{enabled:false,main:[],sub:[]});const key=getYouTubeApiKey();if(!key)return json(res,503,{enabled:true,error:'youtube_api_key_missing'});const limit=Math.min(6,Math.max(1,Number(y.count)||3)),cacheMinutes=Math.min(60,Math.max(1,Number(y.cacheMinutes)||10));try{const [main,sub]=await Promise.all([latestForChannel((y.mainChannelId||'').trim(),limit,cacheMinutes,key),latestForChannel((y.subChannelId||'').trim(),limit,cacheMinutes,key)]);return json(res,200,{enabled:true,main,sub,mainChannelId:y.mainChannelId||'',subChannelId:y.subChannelId||'',updatedAt:new Date().toISOString()})}catch(e){console.error('youtube sync',e);return json(res,502,{enabled:true,error:'youtube_sync_failed',message:e.message})}}
if(pathname==='/api/admin/youtube-key'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});const p=path.join(DATA,'youtube-api-key.txt');if(req.method==='GET')return json(res,200,{configured:!!getYouTubeApiKey(),source:(process.env.YOUTUBE_API_KEY||'').trim()?'environment':(fs.existsSync(p)?'admin':'none')});if(req.method==='POST'){const b=JSON.parse(await readBody(req)||'{}'),k=String(b.apiKey||'').trim();if(!k)return json(res,400,{error:'empty_api_key'});fs.writeFileSync(p,k,'utf8');youtubeCache.clear();return json(res,200,{ok:true,configured:true})}if(req.method==='DELETE'){if(fs.existsSync(p))fs.unlinkSync(p);youtubeCache.clear();return json(res,200,{ok:true,configured:!!(process.env.YOUTUBE_API_KEY||'').trim()})}}
if(pathname==='/api/config'&&req.method==='GET')return json(res,200,loadConfig());
if(pathname==='/api/admin/login'&&req.method==='POST'){if(!ADMIN_PASSWORD)return json(res,503,{error:'admin_password_not_configured'});const b=JSON.parse(await readBody(req)||'{}');if(b.password!==ADMIN_PASSWORD)return json(res,401,{ok:false});const t=crypto.randomBytes(24).toString('hex');sessions.set(t,Date.now());res.setHeader('Set-Cookie',`freedom_admin=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);return json(res,200,{ok:true})}
if(pathname==='/api/admin/logout'&&req.method==='POST'){const t=parseCookies(req).freedom_admin;if(t)sessions.delete(t);res.setHeader('Set-Cookie','freedom_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
if(pathname==='/api/admin/config'){if(!isAdmin(req))return json(res,401,{error:'unauthorized'});if(req.method==='GET')return json(res,200,loadConfig());if(req.method==='PUT'){saveConfig(JSON.parse(await readBody(req)||'{}'));return json(res,200,{ok:true})}}
if(pathname.startsWith('/page/')){const slug=pathname.split('/').filter(Boolean)[1]||'';if(!['deposit','withdraw','trade','benefit'].includes(slug))return send(res,404,'Not found');const tpl=fs.readFileSync(path.join(PUBLIC,'pages','guide.html'),'utf8').replaceAll('__SLUG__',slug);return send(res,200,tpl,'text/html; charset=utf-8')}
if(pathname==='/admin'||pathname==='/admin/')return serveFile(res,path.join(PUBLIC,'admin.html'))||send(res,404,'Not found');
if(pathname==='/')return serveFile(res,path.join(PUBLIC,'index.html'))||send(res,404,'Not found');
const file=path.normalize(path.join(PUBLIC,pathname.replace(/^\//,'')));if(!file.startsWith(PUBLIC))return send(res,403,'Forbidden');if(serveFile(res,file))return;send(res,404,'Not found');
}catch(e){console.error(e);json(res,500,{error:'server_error'})}});
server.listen(PORT,()=>console.log(`FREEDOM site running on port ${PORT}`));
